image: atlassian/default-image:2

pipelines:
  branches: # Pipelines should that will be triggered when a push is made in the below branch
    master:
      - step:
          name: Zip file
          script:
            - zip -r archive.zip node_modules/ app.js package.json
      - step:
          name: Deploy to S3
          script:
            - pipe: atlassian/aws-s3-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                S3_BUCKET: 'asatera-lambda/lambda'
                LOCAL_PATH: '$(pwd)'
                ACL: 'private'
                