image: node:alpine

pipelines:
  branches:
    master:
      - step:
          name: sls deploy
          caches:
            - node
          script:
            - npm install
            - pipe: atlassian/serverless-deploy:1.1.1
            variables:
              AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
                AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
                COMMAND: 'sls deploy'
