image: node

pipelines:
  branches:
    master:
      - step:
          name: sls deploy
          script:
            - npm install -g serverless-offline
            - pipe: atlassian/serverless-deploy:1.1.1
              variables:
                AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
                AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
          
