service: aws-lambda-api-service
#variablesResolutionMode: 20210326
# frameworkVersion: '2'
custom:
  dotenv:
    include: []
provider:
  name: aws
  runtime: nodejs12.x
  #lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
  environment:
    MONGODB_ATLAS_CLUSTER_URI: mongodb+srv://Dev-API-User:y9D3u7GwnfPXIKY7@mongodb-dev.ns6ky.mongodb.net/NewsAPI

functions:
  listArticles:
    handler: handlers/articles_handler.list
    timeout: 60
    events:
      - http:
          path: articles
          method: get
          cors: true
  showArticle:
    handler: handlers/articles_handler.show
    timeout: 60
    events:
      - http:
          path: articles/{id}
          method: get
          cors: true
  listSources:
    handler: handlers/sources_handler.list
    timeout: 60
    events:
      - http:
          path: sources
          method: get
          cors: true
  showSource:
    handler: handlers/sources_handler.show
    timeout: 60
    events:
      - http:
          path: sources/{id}
          method: get
          cors: true

  updateSource:
    handler: handlers/sources_handler.update
    timeout: 60
    events:
      - http:
          path: sources/{id}
          method: put
          cors: true
  createSource:
    handler: handlers/sources_handler.create
    timeout: 60
    events:
      - http:
          path: sources
          method: post
          cors: true

  removeSource:
    handler: handlers/sources_handler.remove
    timeout: 60
    events:
      - http:
          path: sources/{id}
          method: delete
          cors: true
  listSubscriptions:
    handler: handlers/subscriptions_handler.list
    timeout: 60
    events:
      - http:
          path: subscriptions
          method: get
          cors: true
  createUser:
    handler: handlers/users_handler.create
    timeout: 60
    events:
      - http:
          path: users
          method: post
          cors: true
  changePassword:
    handler: handlers/users_handler.recover_password
    timeout: 60
    events:
      - http:
          path: users/recover
          method: post
          cors: true
  userMe:
    handler: handlers/users_handler.me
    timeout: 60
    events:
      - http:
          path: users/me
          method: get
          cors: true
  getApiKey:
    handler: handlers/users_handler.get_api_key
    timeout: 60
    events:
      - http:
          path: users/key
          method: get
          cors: true
  getUsage:
    handler: handlers/users_handler.get_usage
    timeout: 60
    events:
      - http:
          path: users/usage
          method: get
          cors: true
  removeUsers:
    handler: handlers/users_handler.remove
    timeout: 60
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
  updateUser:
    handler: handlers/users_handler.update
    timeout: 60
    events:
      - http:
          path: users/{id}
          method: patch
          cors: true
  updateUserPassword:
    handler: handlers/users_handler.change_password
    timeout: 60
    events:
      - http:
          path: users/password
          method: post
          cors: true
  userRegister:
    handler: handlers/users_handler.register
    timeout: 60
    events:
      - http:
          path: users/signin
          method: post
          cors: true
  userLogin:
    handler: handlers/users_handler.login
    timeout: 60
    events:
      - http:
          path: users/login
          method: post
          cors: true

  updateRequestsPerCycle:
    handler: handlers/subscriptions_handler.updateRequestsPerCycle
    timeout: 60
    events:
      - schedule: cron(0 0 * * ? *)

useDotenv: true
plugins:
  - serverless-offline
  - serverless-middleware
  - serverless-dotenv-plugin
