service: aws-lambda-api-service
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: us-east-1
functions:
  listArticles:
    handler: handlers/articles_handler.list 
    events:
      - http:
          path: articles
          method: get
          cors: true
  showArticle:
    handler: handlers/articles_handler.show
    events:
      - http:
          path: articles/{id}
          method: get
          cors: true
  listSources:
    handler: handlers/sources_handler.list
    events:
      - http:
          path: sources
          method: get
          cors: true
  showSource:
    handler: handlers/sources_handler.show
    events:
      - http:
          path: sources/{id}
          method: get
          cors: true
  updateSource:
    handler: handlers/sources_handler.update
    events:
      - http:
          path: sources/{id}
          method: put
          cors: true
  createSource:
    handler: handlers/sources_handler.create
    events:
      - http:
          path: sources
          method: post
          cors: true
  removeSource:
    handler: handlers/sources_handler.remove
    events:
      - http:
          path: sources/{id}
          method: delete
          cors: true
  listSubscriptions:
    handler: handlers/subscriptions_handler.list 
    events:
      - http:
          path: subscriptions
          method: get
          cors: true
  createUser:
    handler: handlers/users_handler.create
    events:
      - http:
          path: users
          method: post
          cors: true
  userMe:
    handler: handlers/users_handler.me 
    events:
      - http:
          path: users/me
          method: get
          cors: true
  getApiKey:
    handler: handlers/users_handler.get_api_key 
    events:
      - http:
          path: users/key
          method: get
          cors: true
  getUsage:
    handler: handlers/users_handler.get_usage 
    events:
      - http:
          path: users/usage
          method: get
          cors: true
  removeUsers:
    handler: handlers/users_handler.remove
    events:
      - http:
          path: users/{id}
          method: delete
          cors: true
  updateUser:
    handler: handlers/users_handler.update
    events:
      - http:
          path: users/{id}
          method: patch
          cors: true
  userRegister:
    handler: handlers/users_handler.register
    events:
      - http:
          path: users/signin
          method: post
          cors: true
  userLogin:
    handler: handlers/users_handler.login
    events:
      - http:
          path: users/login
          method: post
          cors: true
  userActivate:
    handler: handlers/users_handler.activate
    events:
      - http:
          path: users/activate/{token}
          method: get
          cors: true
useDotenv: true
plugins:
  - serverless-offline